---
image: ubuntu:latest

stages:
  - test
  - build
  - deploy

variables:
  GIT_DEPTH: 0

test:
  stage: test
  variables:
    VERIFY_DEPLOYMENT: 1
  script: |
    echo "Running tests"

build:
  stage: test
  needs:
    - test
  variables:
    VERIFY_DEPLOYMENT: 1
  script: |
    echo "Running build"

deploy:
  stage: deploy
  needs:
    - build
  variables:
    VERIFY_DEPLOYMENT: 1
  script: |
    echo "Running deploy"