---
image: ubuntu:latest

stages:
  - test
  - build
  - deploy

.common_vars: &common_vars
  ENV: prod
  ALLOW_DEPLOY: ${ALLOW_DEPLOY}
  SEND_NOTIFICATIONS: 1
  INCLUDE: ${INCLUDE}

include:
  - to_include/.gitlab-ci.tests.yml

default:
  before_script:
    - echo "Downloading  prerequisites"

build:
  stage: build
  needs:
    - trivy
    - snyk
    - selenium
  variables:
    <<: *common_vars
    BUILD_IMAGES: 1
  trigger:
    include: to_include/.gitlab-ci.build.yml
  only:
    variables:
      - $INCLUDE == "1"

deploy:
  stage: deploy
  needs:
    - build
  variables:
    <<: *common_vars
    DEPLOY_IMAGES: 1
  trigger:
    include: to_include/.gitlab-ci.deploy.yml
  only:
    variables:
      - $INCLUDE == "1"