
name: Dependecies between jobs
run-name: ${{ github.actor }} runs demo dependecies between jobs

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          echo "running tests"
          sleep 10
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: echo "builing image" && sleep 10

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          echo "deploying to prod"
          sleep 10