name: Matrix jobs
run-name: ${{ github.actor }} runs demo matrix jobs

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - docker_images/**

jobs:
  getFolders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Changed Folders
        id: changed_folders
        uses: tj-actions/changed-files@v35.4.4
        with:
          json: "true"
          dir_names: "true"
          dir_names_max_depth: 2
          files: docker_images/

      - name: Set json matrix
        id: set-matrix
        if: steps.changed_folders.outputs.any_changed == 'true'
        run: echo "matrix=${{ steps.changed_folders.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  customMatrix:
    runs-on: ubuntu-latest
    needs: [getFolders]
    if: needs.getFolders.outputs.matrix != ''
    strategy:
      matrix:
        folders: ${{ fromJSON(needs.getFolders.outputs.matrix) }}
        envs: ["dev", "stage", "prod"]
    steps:
      - uses: actions/checkout@v3
      - name: Building docker image in ${{ matrix.folders }}
        if: github.event_name == 'pull_request'
        id: tf_plan
        run: |
          echo Working in ${{ matrix.folders }} for ${{ matrix.envs }}
          cd ${{ matrix.folders }}
          echo "### ${{ matrix.folders }}" >> Dockerfile 
          cp Dockerfile tfplan
          mkdir -p $GITHUB_WORKSPACE/plan
          cp tfplan $GITHUB_WORKSPACE/plan
          path=$(echo "${{ matrix.folders }}" | tr '/' '-')
          echo "tf_plan_name=$path-tfplan" >> $GITHUB_OUTPUT
          ls -la
      - name: Save artifact for ${{ matrix.folders }}
        if: github.event_name == 'pull_request'
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tf_plan.outputs.tf_plan_name }}
          path: ${{ github.workspace }}/plan

      - run: mkdir -p $GITHUB_WORKSPACE/get-plan
          
      - name: Get artifact
        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: get-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ steps.tf_plan.outputs.tf_plan_name }}
          # workflow: plan.yml
          path: ${{ github.workspace }}/get-plan/${{ steps.tf_plan.outputs.tf_plan_name }}

      - name: Show plan
        run: |
          ls -la
          cd ${{ github.workspace }}/get-plan
          ls -la
          cat ${{ github.workspace }}/get-plan/${{ steps.tf_plan.outputs.tf_plan_name }}
