name: Matrix jobs
run-name: ${{ github.actor }} runs demo matrix jobs

on:
  push:
    branches:
      - main
    paths:
      - docker_images/**

jobs:
  getFolders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Changed Folders
        id: changed_folders
        uses: tj-actions/changed-files@v35.4.4
        with:
          json: "true"
          dir_names: "true"
          dir_names_max_depth: 2
          files: docker_images/

      - name: Set json matrix
        id: set-matrix
        if: steps.changed_folders.outputs.any_changed == 'true'
        run: echo "matrix=${{ steps.changed_folders.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  customMatrix:
    runs-on: ubuntu-latest
    needs: [getFolders]
    if: needs.getFolders.outputs.matrix != ''
    strategy:
      matrix:
        folders: ${{ fromJSON(needs.getFolders.outputs.matrix) }}
        envs: ["dev", "stage", "prod"]
    steps:
      - uses: actions/checkout@v3
      - name: Building docker image in ${{ matrix.folders }}
        run: |
          echo Working in ${{ matrix.folders }} for ${{ matrix.envs }}
          cd ${{ matrix.folders }}
          ls -la

