

name: Parallel and dependecies between jobs
run-name: ${{ github.actor }} runs demo parallel and dependecies between jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: echo "builing image" && sleep 10
  trivy:
    name: Testing with trivy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          echo "running tests"
          sleep 10
  snyk:
    name: Testing with snyk
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          echo "running tests"
          sleep 10
  sonarqube:
    name: Testing with sonarqube
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          echo "running tests"
          sleep 10
  selenium:
    name: Testing with selenium
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          echo "running tests"
          sleep 10

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [trivy, snyk, sonarqube, selenium]
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          echo "deploying to prod"
          sleep 10